name: COM-Warfare
version: 2.1.1
main: com.rhetorical.cod.Main
description: Call of Duty Multiplayer recreated for use in Minecraft!
api-version: 1.13
commands:
  cod:
    description: Base command for COM-Warfare.
    usage: /<command>
  comr:
    description: Base command for COM-Warfare.
    usage: /<command>
  com:
    description: Base command for COM-Warfare.
    usage: /<command>