name: COM-Warfare
author: Mr_Rhetorical
version: 2.5.0
api-version: 1.13
main: com.rhetorical.cod.Main
description: Call of Duty Multiplayer recreated for use in Minecraft!
commands:
  cod:
    description: Base command for COM-Warfare.
    usage: /<command>
  comr:
    description: Base command for COM-Warfare.
    usage: /<command>
  com:
    description: Base command for COM-Warfare.
    usage: /<command>
  war:
    description: Base command for COM-Warfare.
    usage: /<command>