lobbyTime: 70
minPlayers: 6
gameTime:
  TDM: 600
  FFA: 600
  RSB: 600
defaultHealth: 100
maxLevel: 55
maxPrestigeLevel: 10
sql:
  api_key: none
translate:
  api_key: none
maxScore:
  TDM: 75
  RSB: 75
  FFA: 30
  KC: 50
  DOM: 200
  CTF: 3
  INFECT: 120
  OITC: 3

RankTiers:
  0:
    name: default
    kill:
      xp: 100
      credits: 1
    levelCredits: 0
  1:
    name: donator
    kill:
      xp: 100
      credits: 1
    levelCredits: 1