name: CallofMinecraftRemastered
version: 2.0.0
main: com.rhetorical.cod.Main
description: Call of Duty Multiplayer in Minecraft!
commands:
  cod:
    description: Main command for COM Warfare
    usage: /{command}