name: COM-Warfare
version: 2.1.0
main: com.rhetorical.cod.Main
description: Call of Duty Multiplayer recreated for use in Minecraft!
commands:
  cod:
    description: Base command for COM-Warfare.
    usage: /<command>